name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags like v1.0.0

jobs:
  release:
    name: Generate GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: git fetch --prune --unshallow

      - name: Extract changelog for tag
        id: extract_changelog
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          CHANGELOG=$(awk "/## \${TAG#v}\/,/^## /" CHANGELOG.md | sed '$d')
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.extract_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
